# Generated by Django 4.2.16 on 2024-12-12 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
    ]
